#!/usr/bin/env bash

# make_assignment.sh will replace the lines here, DO NOT REMOVE
REPLACE_NAME
REPLACE_SOLUTION
REPLACE_REPO_NAME

BASE_DIR=/autograder/$REPO_NAME

echo "BASE_DIR = $BASE_DIR"

# update git repo
cd $BASE_DIR
git pull
# I think the next line is only necessary if you change the requirements after the first version of the assignment
pip3 install -r $BASE_DIR/requirements.txt

# change to assignment directory
cd $BASE_DIR/$NAME

# delete any solution files or folders in the git repo
rm -rf $SOLUTION

# copy student submission to folder
cp -r /autograder/submission/* ./

echo "Running test runner"
python3 $BASE_DIR/gradescope_base/run_tests.py
echo "Done running test runner"
